### ISSUE TITLE
Visualizer - error parsing file

### ISSUE THREAD

**Issue by carljoseph** [verveguy/tana-helper#3] opened 2023-09-12 00:48 UTC
When uploading my JSON export from Tana, I get the following error in the console. Same thing happened with different Tana export files.

```
GraphWorkspace.tsx:157 
kg {message: 'Request failed with status code 422', name: 'AxiosError', code: 'ERR_BAD_REQUEST', config: {…}, request: XMLHttpRequest, …}
code: "ERR_BAD_REQUEST"
config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
message: "Request failed with status code 422"
name: "AxiosError"
request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
response: {data: {…}, status: 422, statusText: 'Unprocessable Entity', headers: Fg, config: {…}, …}
stack: "AxiosError: Request failed with status code 422\n    at p$ (http://127.0.0.1:8000/static/Graph.js:4307:958)\n    at XMLHttpRequest.y (http://127.0.0.1:8000/static/Graph.js:4307:4069)"
[[Prototype]]: Error
```

Let me know if you want any specific portion of this to help debug

**Comment by verveguy** [comment] 2023-11-28 13:59
Hmm. Thanks for the report and sorry I didn't see it until just now! I'll see if I can puzzle it out.

**Comment by carljoseph** [comment] 2023-12-11 05:21
Just trying this again and get an "422 unprocessable entity" error. Tried again with different json files and still the same error. Am using the prebuilt Mac OS X dmg.

```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO     11 Dec 2023 | 16:17:14 | MainThread |                        main.py:77
         txid=7139845562848944128 start request path=/ui/graph                  
INFO     11 Dec 2023 | 16:17:14 | MainThread |                        main.py:84
         txid=7139845562848944128 completed_in=1.15ms status_code=200           
INFO:     127.0.0.1:51819 - "GET /ui/graph HTTP/1.1" 200 OK
INFO     11 Dec 2023 | 16:17:14 | MainThread |                        main.py:77
         txid=7139845563075436544 start request path=/static/Graph.js           
INFO     11 Dec 2023 | 16:17:14 | MainThread |                        main.py:84
         txid=7139845563075436544 completed_in=7.21ms status_code=200           
INFO:     127.0.0.1:51819 - "GET /Graph.js HTTP/1.1" 200 OK
INFO     11 Dec 2023 | 16:17:14 | MainThread |                        main.py:77
         txid=7139845564811878400 start request path=/favicon.ico               
INFO     11 Dec 2023 | 16:17:14 | MainThread |                        main.py:84
         txid=7139845564811878400 completed_in=1.33ms status_code=200           
INFO:     127.0.0.1:51819 - "GET /favicon.ico HTTP/1.1" 200 OK
INFO     11 Dec 2023 | 16:17:44 | MainThread |                        main.py:77
         txid=7139845689579839488 start request path=/graph                     
INFO     11 Dec 2023 | 16:17:58 | MainThread |                        main.py:84
         txid=7139845689579839488 completed_in=13883.43ms                       
         status_code=422                                                        
INFO:     127.0.0.1:51820 - "POST /graph HTTP/1.1" 422 Unprocessable Entity
INFO     11 Dec 2023 | 16:18:25 | MainThread | txid=7139845861378531328 start request         main.py:77
         path=/static/Graph.js.map                                                                      
INFO     11 Dec 2023 | 16:18:25 | MainThread | txid=7139845861378531328 completed_in=1.72ms   main.py:84
         status_code=200                                                                                
INFO:     127.0.0.1:51833 - "GET /Graph.js.map HTTP/1.1" 200 OK
INFO     11 Dec 2023 | 16:18:31 | MainThread | txid=7139845885856489472 start request         main.py:77
         path=/graph                                                                                    
INFO     11 Dec 2023 | 16:18:31 | MainThread | txid=7139845885856489472 completed_in=0.79ms   main.py:84
         status_code=405                                                                                
INFO:     127.0.0.1:51856 - "GET /graph HTTP/1.1" 405 Method Not Allowed
INFO     11 Dec 2023 | 16:18:57 | MainThread | txid=7139845997529833472 start request         main.py:77
         path=/graph                                                                                    
INFO     11 Dec 2023 | 16:18:58 | MainThread | txid=7139845997529833472 completed_in=874.64ms main.py:84
         status_code=422                                                                                
INFO:     127.0.0.1:51857 - "POST /graph HTTP/1.1" 422 Unprocessable Entity
```

**Comment by verveguy** [comment] 2023-12-11 22:13
Thanks for retesting on the latest packaged builds. 

I'm guessing that something has changed in the header format of the Tana export format and I'm too strict on checking. (Thanks, pydantic!). I'll spin up a test cycle and figure out what needs fixing.

**Comment by verveguy** [comment] 2023-12-11 23:17
OK. So the first problem is that Pydantic optional field handling changed and I didn't pick up on it. Sorry! Working on the fix.

**Comment by verveguy** [comment] 2023-12-11 23:49
I found some data gremlins (_ownerId references to nodes that do not exist...). Those are now ignored. Unsure what this implies about my Tana workspace....

**Comment by verveguy** [comment] 2023-12-12 00:01
New release built and published as [0.0.3](https://github.com/verveguy/tana-helper/releases/tag/0.0.3).

Please confirm when you can.

**Comment by carljoseph** [comment] 2023-12-12 00:22
Thanks for the quick look at this. Still getting the same error unfortunately. Is there a way I can send you my json file if that might help? Or some other debug info?

```
INFO     12 Dec 2023 | 11:21:27 | MainThread |                        main.py:86
         txid=7140133514632142848 start request path=/graph                     
INFO     12 Dec 2023 | 11:21:28 | MainThread |                        main.py:93
         txid=7140133514632142848 completed_in=1570.25ms                        
         status_code=422                                                        
INFO:     127.0.0.1:56914 - "POST /graph HTTP/1.1" 422 Unprocessable Entity
```

**Comment by verveguy** [comment] 2024-01-06 22:57
Looks like we resolved this and confirmed via slack messages back on Dec 11. Closing out this issue.

**Closed by verveguy** 2024-01-06 22:57 UTC
